"""Structured, transport-safe A-package errors."""
from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field
from .versions import ERROR_SCHEMA_VERSION

class ErrorCode(StrEnum):
    OK = "OK"
    INVALID_PROTOCOL = "INVALID_PROTOCOL"
    INVALID_REQUEST = "INVALID_REQUEST"
    REQUEST_CONFLICT = "REQUEST_CONFLICT"
    AWAITING_USER_CONFIRMATION = "AWAITING_USER_CONFIRMATION"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_IDENTITY_MISMATCH = "WORKSPACE_IDENTITY_MISMATCH"
    WORKSPACE_IN_USE = "WORKSPACE_IN_USE"
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    TRANSACTION_CONFLICT = "TRANSACTION_CONFLICT"
    INVALID_TRANSACTION_STATE = "INVALID_TRANSACTION_STATE"
    INTENT_CONFLICT = "INTENT_CONFLICT"
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
    RECORD_REVISION_CONFLICT = "RECORD_REVISION_CONFLICT"
    IMMUTABLE_RECORD_CONFLICT = "IMMUTABLE_RECORD_CONFLICT"
    OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
    OBJECT_DIGEST_MISMATCH = "OBJECT_DIGEST_MISMATCH"
    INDEX_REBUILD_REQUIRED = "INDEX_REBUILD_REQUIRED"
    INTEGRITY_CHECK_FAILED = "INTEGRITY_CHECK_FAILED"
    STORAGE_NOT_WRITABLE = "STORAGE_NOT_WRITABLE"
    ATOMIC_PUBLISH_FAILED = "ATOMIC_PUBLISH_FAILED"
    BACKUP_FAILED = "BACKUP_FAILED"
    MIGRATION_FAILED = "MIGRATION_FAILED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    CONNECTIVITY_FAILED = "CONNECTIVITY_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_CURSOR = "invalid_cursor"
    MAINTENANCE_REQUIRED = "maintenance_required"

class ErrorDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)
    schema_version: str = ERROR_SCHEMA_VERSION
    code: ErrorCode | str
    message: str = Field(min_length=1, max_length=1000)
    retryable: bool = False
    next_step: str = Field(min_length=1, max_length=500)
    request_id: str | None = None
    intent_id: str | None = None

